version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: multi_model_ai_api
    volumes:
      - ./:/app
      - api_data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - multi_model_network

  # Optional: Separate database container if you want to use a more robust DB like PostgreSQL
  # db:
  #   image: postgres:14-alpine
  #   container_name: multi_model_ai_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - multi_model_network

networks:
  multi_model_network:
    driver: bridge

volumes:
  api_data:
  # postgres_data:  # Uncomment if using PostgreSQL